# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54bbe2f6b85cc33d671ab8ac09eae2cd6e73f257b39e4311ff55572c6c61d3e576ed15f772e09e507d98a1544c5d59849743c7a74e5ecacdee5fe9172ba4816c

test:
  secret_key_base: 9e96c59625db90242a460a043c1aca64bb5cbc6286030f5b3a4e0ed9a6e6f4afd17e01dfe898b15454d835949a890acd1e4440a916d00e6106c738c07eab5040

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
